#!/bin/bash
SCRIPT_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"


if [[ -f $SCRIPT_FILE ]]; then
echo File allready here
code $SCRIPT_FILE
else 

# touch $SCRIPT_FILE
echo '#!/bin/bash' > $SCRIPT_FILE
chmod +x $SCRIPT_FILE
code $SCRIPT_FILE
#touch $1

fi
